gfcli:
  gen:
    service:
      srcFolder: internal/logic       # 源文件的路径
      dstFolder: internal/service     # 目标文件的路径
      dstFileNameCase: Snake          # 目标文件的命名规则
      watchFile:                      # 监控的文件
      stPattern: ^([a-zA-Z]\w+)Logic$ # 结构体的命名规则
      packages:                       # 只生成指定包下的目标文件
      importPrefix:                   # 引入文件的包前缀
      clear: false                    # 清理目标文件
